name: kghm_wiedza
description: Mobile application made for KGHM during CuValley Hack 2023
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.10

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  equatable: ^2.0.3
  connectivity_plus: ^2.3.3
  bloc_concurrency: ^0.2.0
  stream_transform: ^2.1.0
  flutter_local_notifications: ^9.2.0
  formz: ^0.4.0
  url_launcher: ^6.1.6
  flutter_appauth: ^4.2.1
  flutter_secure_storage: ^6.0.0
  http: ^0.13.5
  go_router: ^6.5.0
  rxdart: ^0.27.7
  hydrated_bloc: ^9.0.0
  user_repository:
    path: packages/user_repository
  authentication_repository:
    path: packages/authentication_repository
  home_repository:
    path: packages/home_repository

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: lib/assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: lib/assets/fonts/Roboto/Roboto-Bold.ttf
  assets:
    - lib/assets/icons/kghm.png
    - lib/assets/images/info.png
    - lib/assets/images/job.png
    - lib/assets/images/resources.png
    - lib/assets/images/stock.png
    - lib/assets/images/info.svg