name: authentication_repository
description: A repository that handles authentication related requests.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
  flutter_appauth: ^4.2.1
  flutter_secure_storage: ^7.0.1
  http: ^0.13.5
  aad_oauth: ^0.4.2
